[project]
name = "convoca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.1.1",
    "django-htmx>=1.29.0",
    "gunicorn>=26.2.0",
    "psycopg[binary]>=3.3.6",
    "python-decouple>=3.8",
    "whitenoise>=6.12.0",
    "xhtml2pdf>=0.2.20",
]

[dependency-groups]
dev = [
    "django-stubs>=6.1.1",
    "model-bakery>=1.24.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.14.0",
    "pytest-html>=4.2.0",
    "ruff>=0.16.8",
]

[tool.ruff]
exclude = ["*/migrations/*"]

[tool.ruff.lint]
ignore = ["RUF012"]
