[pytest]
DJANGO_SETTINGS_MODULE = config.settings.local
python_files = test_*.py
testpaths = apps
addopts = --reuse-db --cov=apps --cov-report=html --cov-report=term-missing --html=docs/informe-pruebas.html --self-contained-html
filterwarnings =
    ignore:No directory at:UserWarning