# Generated by Django 6.1.1 on 2026-09-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('inicio', models.DateField(verbose_name='inicio')),
                ('fin', models.DateField(verbose_name='fin')),
                ('fecha_cierre_propuestas', models.DateField(verbose_name='fecha de cierre de propuestas')),
                ('cupo_minimo', models.PositiveSmallIntegerField(default=20, verbose_name='cupo mínimo')),
                ('abierto', models.BooleanField(default=True, verbose_name='abierto')),
            ],
            options={
                'verbose_name': 'periodo',
                'verbose_name_plural': 'periodos',
            },
        ),
    ]
