# Generated by Django 6.1.1 on 2026-09-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'facultad',
                'verbose_name_plural': 'facultades',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='academico.facultad', verbose_name='facultad')),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('creditos', models.PositiveSmallIntegerField(verbose_name='créditos')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='academico.programa', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'asignatura',
                'verbose_name_plural': 'asignaturas',
            },
        ),
    ]
