# Generated by Django 6.1.1 on 2026-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='código'),
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('programa', 'codigo'), name='unico_codigo_por_programa'),
        ),
    ]
