# Generated by Django 6.1.1 on 2026-09-22 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('periodos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('QUORUM', 'Quórum'), ('RADICADA', 'Radicada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ABIERTA', max_length=10, verbose_name='estado')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas', to='academico.asignatura', verbose_name='asignatura')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creador')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas', to='academico.docente', verbose_name='docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas', to='periodos.periodo', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'propuesta',
                'verbose_name_plural': 'propuestas',
            },
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesiones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesiones', to='propuestas.propuesta', verbose_name='propuesta')),
            ],
            options={
                'verbose_name': 'adhesión',
                'verbose_name_plural': 'adhesiones',
            },
        ),
        migrations.AddConstraint(
            model_name='propuesta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'RECHAZADA'), _negated=True), fields=('asignatura', 'periodo'), name='unica_propuesta_activa_por_asignatura_periodo'),
        ),
        migrations.AddConstraint(
            model_name='adhesion',
            constraint=models.UniqueConstraint(fields=('propuesta', 'usuario'), name='unica_adhesion_por_propuesta_y_usuario'),
        ),
    ]
